Handle early `git commit --patch` quits more gracefully
When a `git commit --patch` invocation is canceled by the user by
responding with 'q' before anything got added, git prints a status
message.
In our context such a status message is only confusing and it certainly
doesn't add any value. As such, with this change we split the `git
commit --patch` into a `git add --patch` followed by a `git commit`, if
hunks were previously added. If no hunks were added we just continue.

diff --git a/git-split b/git-split
--- a/git-split
+++ b/git-split
@@ -12,7 +12,7 @@ cd_to_toplevel
 require_clean_work_tree $cmd
 
 has_no_changes() {
-  git diff --quiet --exit-code
+  git diff --quiet --exit-code ${@}
 }
 
 revert_changes() {
@@ -36,7 +36,18 @@ git reset HEAD^ --quiet
 git add --intent-to-add $(git show --no-prefix --name-only --format='' "${head}" | xargs)
 
 while :; do
-  git commit --no-verify --patch --reedit-message "${head}" || true
+  # We use separate git add & git commit invocation because git commit
+  # --patch prints undesirable status stuff when stopped directly with
+  # 'q' without adding anything.
+  git add --patch
+  # Only attempt to commit something if the user staged changes.
+  if ! has_no_changes --staged; then
+    # On error, be sure to revert any staged changes to give the user a
+    # chance to redo them.
+    git commit --no-verify --reedit-message "${head}" \
+      || git reset HEAD --quiet \
+      || true
+  fi
 
   if has_no_changes; then
     # If the user already included all changes then we are done.
